# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Dummy workflow

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/head/release1'
    steps:
    - name: Step1Job1
      run: echo "Step1Job1"

  job2:
    runs-on: ubuntu-latest
#   if: github.ref == 'refs/head/release3'
    steps:
    - name: Step1Job2
      run: echo "Step1Job2
    


